image:
  repository: ghcr.io/baruchihalamish20/order-service
  tag: "3bf801b"
env:
  - name: SECRET_KEY
    value: "stage-secret-order"
  - name: APP_ENV
    value: "stage"
service:
  type: NodePort
  port: 80
  nodePort: 30022

