image:
  repository: ghcr.io/irinarozalio/order-service
  tag: "7c952ec"
env:
  - name: SECRET_KEY
    value: "stage-secret-order"
  - name: APP_ENV
    value: "stage"
service:
  type: LoadBalancer
  port: 80
  nodePort: 30022

